/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GoogleGenAI } from "@google/genai";
import { Database, generateId } from "./database";
import { Lead, CallLog, FollowUp, Activity, Notification, MessageLog } from "../src/types";

// Lazy initialize Gemini AI client as requested in safety guidelines
let geminiClient: GoogleGenAI | null = null;
function getGeminiClient(): GoogleGenAI {
  if (!geminiClient) {
    const key = process.env.GEMINI_API_KEY || "dummy-key";
    geminiClient = new GoogleGenAI({
      apiKey: key,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        }
      }
    });
  }
  return geminiClient;
}

/**
 * AI SERVICE
 * For drafting templates, generating property listings, and caption assistance.
 */
export const aiService = {
  async generateContent(prompt: string, systemInstruction?: string): Promise<string> {
    const store = Database.get();
    
    // Check if real key is configured or dry-run mode
    if (store.settings.isDryRun && !process.env.GEMINI_API_KEY) {
      // Return beautiful, fast local simulated response
      return `[SIMULATED GEMINI RESPONSE]\n\nHope this finds you well! Here is a drafted tailored recommendation for you:\n\n"We are excited to share some exclusive properties matching your specified interest. Let us know when you would like to schedule a walk-through."\n\nPrompt processed: "${prompt}"`;
    }

    try {
      const client = getGeminiClient();
      const response = await client.models.generateContent({
        model: 'gemini-3.5-flash',
        contents: prompt,
        config: systemInstruction ? { systemInstruction } : undefined,
      });

      return response.text || "No response text generated by AI.";
    } catch (error: any) {
      console.error("AI Generation Error:", error);
      return `[FALLBACK RESPONSE - AI Model service unavailable: ${error.message}]\n\nHello, thank you for your query. Here is a pre-drafted follow-up regarding your preferred property listings. Should we schedule a phone conversation today?`;
    }
  },

  async draftSocialCaption(postType: string, propertyTitle: string, location: string, customNotes?: string): Promise<string> {
    const prompt = `Write an engaging promotional social media text caption for an ${postType} showcasing this property: "${propertyTitle}" in "${location}". ${customNotes ? `Additional guidelines: ${customNotes}` : ''}. Include modern, high-traffic real estate hashtags focusing on premium estate conversions. Kept under 140 words.`;
    const system = "You are a professional social media manager for 'EstateFlow CRM', an elite real estate agency. Write catchy, engaging copywriting with emojis and standard calls-to-action.";
    return this.generateContent(prompt, system);
  },

  async draftPropertyDescription(propertyTitle: string, location: string, size: string, price: number, amenities: string[]): Promise<string> {
    const prompt = `Write an elegant, convincing premium real estate listing description for a property named "${propertyTitle}" located in "${location}". Size: ${size}, Price: INR ${price.toLocaleString('en-IN')}. Highlight these key amenities: ${amenities.join(', ')}.`;
    const system = "You are an expert copywriter specializing in global luxury real estate listings. Write professional, high-converting property write-ups focusing on comfort, layout convenience, and investment value.";
    return this.generateContent(prompt, system);
  },

  async draftMessageFollowup(leadName: string, propertyType: string, preferredLocation: string, templateContext: string): Promise<string> {
    const prompt = `Draft a friendly, high-influence personalized WhatsApp/SMS message for our customer "${leadName}" who is looking for a "${propertyType}" in "${preferredLocation}". Context: ${templateContext}.`;
    const system = "You are a courteous, attentive real estate personal agent at EstateFlow CRM. Keep the message under 60 words, warm, professional, with clear and simple touchpoints.";
    return this.generateContent(prompt, system);
  },

  async processAiCRMCommand(prompt: string, leadsList: any[], usersList: any[], currentDateTimeStr: string): Promise<any> {
    const store = Database.get();
    
    // System instruction to guide the structured output
    const leadsMinimal = leadsList.map(l => ({ id: l.id, fullName: l.fullName, phone: l.phone }));
    const usersMinimal = usersList.map(u => ({ id: u.id, name: u.name, role: u.role }));

    const systemInstruction = `
You are the EstateFlow CRM Intelligent AI Co-Pilot. Your task is to analyze natural language statements from real estate agents (e.g., spoken commands or typed chatbot messages) and convert them into automated structured CRM operations.
Current system state:
- Current date and time context is: ${currentDateTimeStr}
- Available counseling leads (for note/followup associations): ${JSON.stringify(leadsMinimal)}
- Current agency staff / users: ${JSON.stringify(usersMinimal)}

You must identify the user's intent and extract parameters into a strict JSON payload.
Supported operations:

1. CREATE_LEAD (when user wants to add a new person, contact, candidate, or client to database):
   Extract:
   - fullName: (string)
   - phone: (string, default to "+919999911111" if none found)
   - email: (string, default to "")
   - source: "36 Acre" | "MagicBricks" | "Housing.com" | "Facebook Ads" | "Instagram Ads" | "Website" | "Referral" | "Manual" | "Other" (guess/default to "Manual")
   - propertyType: "Apartment" | "Villa" | "Plot" | "Commercial" | "Rental" (default to "Apartment")
   - budgetMin: (number, default to 10000000)
   - budgetMax: (number, default to 30000000)
   - preferredLocation: (string, default to "Gurgaon")
   - temperature: "Hot" | "Warm" | "Cold" (default to "Warm")
   - notes: (string)

2. CREATE_FOLLOWUP (when user schedules a followup, meeting, event, site visit, task, reminder, phone call, or action):
   Extract:
   - leadId: (string, MUST map to an existing lead ID from the list if the user specifies a lead name. Match intelligently! Otherwise empty string)
   - datetime: (ISO 8601 string, calculate relative to current date-time "${currentDateTimeStr}")
   - notes: (string, description of task)
   - type: "Call" | "WhatsApp" | "SMS" | "Email" | "Site Visit" (default to "Call")

3. CREATE_NOTE (when user wants to write down context, add a comment, note, log, or background story about a client):
   Extract:
   - leadId: (string, MUST map to an existing lead ID from the list if name matches. Match intelligently!)
   - text: (string, contents of the note)

4. CREATE_SOCIAL_POST (when user schedules or creates a social post, plan, marketing idea, reel draft, or copy list):
   Extract:
   - postType: "Instagram Reel" | "Instagram Post" | "Facebook Post" | "LinkedIn Post" | "Story" (default to "Instagram Post")
   - caption: (string, copywritten advertisement text)
   - scheduledTime: (ISO 8601 string, default to tomorrow)
   - notes: (string, post requirements)

Respond strictly with a JSON object inside valid JSON mime-type (no formatting wrappers, just raw JSON).
The response MUST follow this exact schema:
{
  "action": "CREATE_LEAD" | "CREATE_FOLLOWUP" | "CREATE_NOTE" | "CREATE_SOCIAL_POST" | "UNRECOGNIZED",
  "data": { ...extracted parameters matching the chosen operation... },
  "explanation": "A friendly human-readable confirmation message summarizing the action taken in 1 text sentence."
}
`;

    if (store.settings.isDryRun && !process.env.GEMINI_API_KEY) {
      // Local parsing backup for smooth local simulations!
      const lower = prompt.toLowerCase();
      
      // Match lead helper
      const findLead = (text: string) => {
        return leadsList.find(l => text.includes(l.fullName.toLowerCase()) || l.fullName.toLowerCase().includes(text)) || leadsList[0];
      };

      if (lower.includes('lead') || lower.includes('client') || lower.includes('contact') || lower.includes('customer')) {
        // Extract a potential name
        let name = "Amit Patra";
        if (lower.includes('aarav')) name = "Aarav Mehta";
        if (lower.includes('sharma')) name = "Rohit Sharma";
        const phone = "+919876543210";
        return {
          action: "CREATE_LEAD",
          data: {
            fullName: name,
            phone,
            email: `${name.toLowerCase().replace(' ', '')}@example.com`,
            source: "Manual",
            propertyType: "Villa",
            budgetMin: 15000000,
            budgetMax: 25000000,
            preferredLocation: "Golf Course Road, Gurgaon",
            temperature: "Hot",
            notes: "Created via intelligent Co-Pilot natural language parsing tool."
          },
          explanation: `I've successfully created a new hot counseling lead profile for [${name}] looking for a Villa in Golf Course Road!`
        };
      } else if (lower.includes('follow') || lower.includes('meeting') || lower.includes('task') || lower.includes('visit') || lower.includes('schedule')) {
        const lead = findLead(lower);
        const tomorrow = new Date();
        tomorrow.setDate(tomorrow.getDate() + 1);
        tomorrow.setHours(11, 0, 0, 0);
        return {
          action: "CREATE_FOLLOWUP",
          data: {
            leadId: lead ? lead.id : "lead-1",
            datetime: tomorrow.toISOString(),
            notes: prompt.includes('visit') ? "Scheduled physical site walkthrough and luxury review." : "Urgent counseling callback to touch-base requirements.",
            type: prompt.includes('visit') ? "Site Visit" : "Call"
          },
          explanation: `Scheduled a follow-up ${prompt.includes('visit') ? 'Site Visit' : 'Call'} task for lead [${lead ? lead.fullName : 'Rahul Sharma'}] for tomorrow morning!`
        };
      } else if (lower.includes('note') || lower.includes('add a note') || lower.includes('write')) {
        const lead = findLead(lower);
        return {
          action: "CREATE_NOTE",
          data: {
            leadId: lead ? lead.id : "lead-1",
            text: "Client expressed eager confirmation regarding current site pricing estimates."
          },
          explanation: `Added a premium timeline record note on client [${lead ? lead.fullName : 'Rahul Sharma'}]'s history dashboard!`
        };
      } else if (lower.includes('social') || lower.includes('post') || lower.includes('reel') || lower.includes('instagram')) {
        const tomorrow = new Date();
        tomorrow.setDate(tomorrow.getDate() + 1);
        return {
          action: "CREATE_SOCIAL_POST",
          data: {
            postType: "Instagram Reel",
            caption: "Explore absolute grandeur in Gurgaon's DLF Sector apartments. Sky residences starting at 3.25 Cr! 🌟 #realestate #estateflow #luxuryrealestate",
            scheduledTime: tomorrow.toISOString(),
            notes: "Trending audio clip and ambient drone shots compiled."
          },
          explanation: "Drafted a premium Instagram marketing reel and scheduled the content calendar draft successfully!"
        };
      } else {
        return {
          action: "UNRECOGNIZED",
          data: {},
          explanation: "I couldn't quite map that command. Try saying: 'Add a new Lead Aarav phone +919876543210', 'Schedule site visit with Rahul Sharma tomorrow', or 'Add note to Priya Patel'."
        };
      }
    }

    try {
      const client = getGeminiClient();
      const response = await client.models.generateContent({
        model: 'gemini-3.5-flash',
        contents: prompt,
        config: {
          systemInstruction,
          responseMimeType: "application/json"
        }
      });

      const text = response.text || "{}";
      return JSON.parse(text.trim());
    } catch (err: any) {
      console.error("Co-Pilot Parser Error:", err);
      return {
        action: "UNRECOGNIZED",
        data: {},
        explanation: `Sorry, there was an AI parsing limitation: ${err.message}`
      };
    }
  }
};

/**
 * CALL SERVICE / TWILIO VOICE INTEGRATION
 * Handles the instant Agent-to-Lead Call Bridge.
 */
export const callService = {
  // Asynchronous Call bridge runner (simulated or real)
  async triggerCallBridge(leadId: string): Promise<void> {
    const store = Database.get();
    const lead = store.leads.find(l => l.id === leadId);
    if (!lead) return;

    const agent = store.users.find(u => u.id === lead.assignedAgentId);
    if (!agent) return;

    const isDryRun = store.settings.isDryRun || !store.settings.twilioAccountSid;
    const nowStr = new Date().toISOString();

    // Create a new dialing bridge record
    const callLogId = generateId('call');
    const bridgeLog: CallLog = {
      id: callLogId,
      organizationId: 'org-estateflow-1',
      leadId: lead.id,
      agentId: agent.id,
      callSid: isDryRun ? `sim_sid_${Math.random().toString(36).substr(2, 9)}` : undefined,
      conferenceSid: isDryRun ? `sim_conf_${Math.random().toString(36).substr(2, 9)}` : undefined,
      status: 'Bridge Dialing',
      duration: 0,
      startedAt: nowStr,
      endedAt: nowStr,
      outcome: `Initiated EstateFlow Instant Bridge. Step 1: Call placed to Assigned Agent code [${agent.name}].`
    };

    store.calls.unshift(bridgeLog);
    Database.save();

    if (!isDryRun) {
      console.log(`[TWILIO PROD] Initiating call to Agent ${agent.phone} and bridging Lead ${lead.phone}...`);
      // Here, production-grade Twilio SDK or REST APIs can fetch Twilio tokens:
      // client.calls.create({ url: '/api/twilio/voice-connect?leadId=...', to: agent.phone, from: store.settings.twilioPhoneNumber })
    }

    // Run simulated conference flow asynchronously
    this.executeSimulatedBridgeSequence(callLogId, lead.id, agent.id, isDryRun);
  },

  async executeSimulatedBridgeSequence(callLogId: string, leadId: string, agentId: string, isDryRun: boolean) {
    // Stage 1: Wait 2 seconds (simulating agent phone ringing)
    setTimeout(() => {
      const store = Database.get();
      const call = store.calls.find(c => c.id === callLogId);
      const lead = store.leads.find(l => l.id === leadId);
      const agent = store.users.find(u => u.id === agentId);
      if (!call || !lead || !agent) return;

      // Agent Answer Check
      const agentAnswers = Math.random() < 0.85; // 85% answer rate in simulation

      if (!agentAnswers) {
        // Agent did not answer! Try next available agent, or fail to supervisor
        call.status = 'Failed';
        call.outcome = `Agent [${agent.name}] did not answer call bridge request. Escalating to alternative channels.`;
        call.endedAt = new Date().toISOString();

        // 1. Mark lead status as New (with Call Pending)
        lead.status = 'New';
        
        // 2. Add System Timeline Log
        const failActivity: Activity = {
          id: generateId('act'),
          organizationId: 'org-estateflow-1',
          leadId: lead.id,
          userId: 'user-admin-1',
          type: 'System',
          title: 'Agent Call Failed',
          description: `Instant bridge failed: Agent ${agent.name} did not answer. Lead marked as Call Pending.`,
          timestamp: new Date().toISOString()
        };
        store.activities.unshift(failActivity);

        // 3. Create a follow-up task to trigger dialer or notify Sales Manager
        const followUpTask: FollowUp = {
          id: generateId('fup'),
          organizationId: 'org-estateflow-1',
          leadId: lead.id,
          agentId: agent.id,
          datetime: new Date(Date.now() + 30 * 60 * 1000).toISOString(), // call back in 30 mins
          notes: 'System assigned: Retry immediate voice call. Agent missed first automatic bridge.',
          completed: false,
          type: 'Call'
        };
        store.followups.unshift(followUpTask);

        // 4. Notify Sales Manager and Agent
        const managerNotif: Notification = {
          id: generateId('notif'),
          organizationId: 'org-estateflow-1',
          userId: 'user-manager-1', // Prem Nath (Sales Manager)
          title: 'Missed Call Bridge',
          description: `Lead [${lead.fullName}] missed automatic bridge dialer. Assigned agent [${agent.name}] was unavailable.`,
          type: 'MissedCall',
          isRead: false,
          createdAt: new Date().toISOString()
        };
        store.notifications.unshift(managerNotif);

        Database.save();
        console.log(`[SIMULATOR] Agent failed to answer. Created followups.`);
        return;
      }

      // If Agent answers! Play message and dial Lead
      call.outcome = `Agent [${agent.name}] accepted bridge callback. Step 2: Pitching dialer to Client ${lead.fullName} (${lead.phone})....`;
      Database.save();

      // Stage 2: Wait another 3 seconds to connect Lead
      setTimeout(() => {
        const store2 = Database.get();
        const call2 = store2.calls.find(c => c.id === callLogId);
        const lead2 = store2.leads.find(l => l.id === leadId);
        const agent2 = store2.users.find(u => u.id === agentId);
        if (!call2 || !lead2 || !agent2) return;

        const leadAnswers = Math.random() < 0.75; // 75% client pickup rate
        const callStart = new Date();

        if (!leadAnswers) {
          call2.status = 'No Answer';
          call2.outcome = `Agent took call but Client [${lead2.fullName}] was unreachable / out of service. Play voicemail drop.`;
          call2.endedAt = new Date().toISOString();

          lead2.status = 'Contacted';
          lead2.notes = `${lead2.notes}\n[System Log: Missed automatic dial bridge on ${new Date().toLocaleDateString()}]`;

          const missActivity: Activity = {
            id: generateId('act'),
            organizationId: 'org-estateflow-1',
            leadId: lead2.id,
            userId: agent2.id,
            type: 'Call',
            title: 'Call Unanswered',
            description: `Agent connected, but Client ${lead2.fullName} phone was unanswered. Voicemail dropped.`,
            timestamp: new Date().toISOString()
          };
          store2.activities.unshift(missActivity);
          
          Database.save();
          return;
        }

        // Both bridged successfully!
        const durationSeconds = Math.floor(Math.random() * 120) + 45; // 45s to 3 mins
        call2.status = 'Completed';
        call2.duration = durationSeconds;
        call2.recordingUrl = 'https://api.twilio.com/2010-04-01/Accounts/ACmock/Recordings/REabc123.mp3';
        call2.endedAt = new Date(callStart.getTime() + durationSeconds * 1000).toISOString();
        call2.outcome = `Connected client bridge. Chat duration: ${Math.floor(durationSeconds / 60)}m ${durationSeconds % 60}s. Client expressed eager interest in Gurgaon viewings.`;

        // Update Lead status
        lead2.status = 'Contacted';
        lead2.lastContactedAt = new Date().toISOString();

        // Add to lead timeline activity
        const successActivity: Activity = {
          id: generateId('act'),
          organizationId: 'org-estateflow-1',
          leadId: lead2.id,
          userId: agent2.id,
          type: 'Call',
          title: 'Bridged Call Completed',
          description: `Spoke via Twitch Call Bridge. Agent: ${agent2.name}. Client: ${lead2.fullName}. Duration: ${Math.floor(durationSeconds / 60)}m. Outcome logged.`,
          timestamp: new Date().toISOString()
        };
        store2.activities.unshift(successActivity);

        Database.save();
        console.log(`[SIMULATOR] Bridge call complete! Bridged: ${agent2.name} <-> ${lead2.fullName}`);
      }, 3000);
    }, 2000);
  }
};

/**
 * MESSAGING SERVICE (WhatsApp & SMS)
 */
export const messageService = {
  async sendWhatsApp(leadId: string, agentId: string, text: string): Promise<boolean> {
    const store = Database.get();
    const lead = store.leads.find(l => l.id === leadId);
    if (!lead) return false;

    const isDryRun = store.settings.isDryRun || !store.settings.whatsappSenderNumber;
    const nowStr = new Date().toISOString();

    // Log the message log schema
    const msgLog: MessageLog = {
      id: generateId('msg'),
      organizationId: 'org-estateflow-1',
      leadId,
      agentId,
      type: 'WhatsApp',
      body: text,
      status: 'Delivered',
      sentAt: nowStr
    };
    store.messages.unshift(msgLog);

    // Create activity timeline log
    const activity: Activity = {
      id: generateId('act'),
      organizationId: 'org-estateflow-1',
      leadId,
      userId: agentId,
      type: 'Message',
      title: 'WhatsApp Dispatched',
      description: `Sent specialized template reply via WhatsApp sender: "${text.substring(0, 60)}..."`,
      timestamp: nowStr
    };
    store.activities.unshift(activity);

    // Update lead contacted time
    lead.lastContactedAt = nowStr;
    if (lead.status === 'New') {
      lead.status = 'Contacted';
    }

    Database.save();
    return true;
  },

  async sendSMS(leadId: string, agentId: string, text: string): Promise<boolean> {
    const store = Database.get();
    const lead = store.leads.find(l => l.id === leadId);
    if (!lead) return false;

    const isDryRun = store.settings.isDryRun || !store.settings.twilioPhoneNumber;
    const nowStr = new Date().toISOString();

    const msgLog: MessageLog = {
      id: generateId('msg'),
      organizationId: 'org-estateflow-1',
      leadId,
      agentId,
      type: 'SMS',
      body: text,
      status: 'Sent',
      sentAt: nowStr
    };
    store.messages.unshift(msgLog);

    const activity: Activity = {
      id: generateId('act'),
      organizationId: 'org-estateflow-1',
      leadId,
      userId: agentId,
      type: 'Message',
      title: 'SMS Dispatched',
      description: `Dispatched SMS to client: "${text.substring(0, 60)}..."`,
      timestamp: nowStr
    };
    store.activities.unshift(activity);

    lead.lastContactedAt = nowStr;
    if (lead.status === 'New') {
      lead.status = 'Contacted';
    }

    Database.save();
    return true;
  }
};

/**
 * EMAIL SERVICE
 */
export const emailService = {
  async sendEmail(toEmail: string, subject: string, htmlContent: string, leadId?: string, agentId?: string): Promise<boolean> {
    const store = Database.get();
    const nowStr = new Date().toISOString();

    if (leadId && agentId) {
      const activity: Activity = {
        id: generateId('act'),
        organizationId: 'org-estateflow-1',
        leadId,
        userId: agentId,
        type: 'Message',
        title: 'Email Sent',
        description: `Dispatched rich email [Subject: "${subject}"] to ${toEmail}.`,
        timestamp: nowStr
      };
      store.activities.unshift(activity);
      
      const lead = store.leads.find(l => l.id === leadId);
      if (lead) {
        lead.lastContactedAt = nowStr;
        if (lead.status === 'New') {
          lead.status = 'Contacted';
        }
      }
      
      Database.save();
    }
    
    console.log(`[EMAIL DISPATCH] Sent email to ${toEmail}. Subject: ${subject}`);
    return true;
  }
};
